global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mcp-server'
    static_configs:
      - targets: ['mcp-monitoring:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'ecommerce-app'
    static_configs:
      - targets: ['host.docker.internal:12000']
    scrape_interval: 15s
    metrics_path: /api/metrics
    scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093